### ISSUE TITLE
Tangent reports "File Write Error" after successful write

### ISSUE THREAD

**Issue by juhrmann** [suchnsuch/Tangent#94]
**Version**: 0.6.7
**OS**: Windows 11
**Environment**: Workspace is on a Synology NAS, the note title (and its file name) contains spaces

**Observed behaviour**: 
- Tangent reports an error (File Write Error), indicating that the note could not be safed.
- The MD file is acutally saved and contains the intended changes.

**Expected behaviour**:
- No error message is displayed after successful file writes.

Relevant logs:
```
INFO  2024-09-05 16:56:03: [messages] opening file \\nas.fritz.box\freigabe\Hans\TangentNotes\Umzug auf neues Smartphone.md
INFO  2024-09-05 16:56:16: [file] updating and saving \\nas.fritz.box\freigabe\Hans\TangentNotes\Umzug auf neues Smartphone.md
ERROR 2024-09-05 16:56:17: [workspace.files] Failed to set contents of \\nas.fritz.box\freigabe\Hans\TangentNotes\Umzug auf neues Smartphone.md TypeError: Cannot read properties of undefined (reading 'path')
    at mapper (C:\Users\micro\AppData\Local\Programs\Tangent\resources\app.asar\__build\bundle\webpack:\tangent_electron\src\common\indexing\Indexer.ts:191:13)
    at mapIterator (C:\Users\micro\AppData\Local\Programs\Tangent\resources\app.asar\__build\bundle\webpack:\tangent_electron\node_modules\@such-n-such\core\lib\iterables.js:76:15)
    at P.next (<anonymous>)
    at zr.onFileContentChanged (C:\Users\micro\AppData\Local\Programs\Tangent\resources\app.asar\__build\bundle\webpack:\tangent_electron\src\common\indexing\Indexer.ts:189:35)
    at di.updateFileContents (C:\Users\micro\AppData\Local\Programs\Tangent\resources\app.asar\__build\bundle\webpack:\tangent_electron\src\main\Workspace.ts:764:24)

ERROR 2024-09-05 16:56:17: [workspace]   Promise 0 failed to complete successfully TypeError: Cannot read properties of undefined (reading 'path')
    at mapper (C:\Users\micro\AppData\Local\Programs\Tangent\resources\app.asar\__build\bundle\webpack:\tangent_electron\src\common\indexing\Indexer.ts:191:13)
    at mapIterator (C:\Users\micro\AppData\Local\Programs\Tangent\resources\app.asar\__build\bundle\webpack:\tangent_electron\node_modules\@such-n-such\core\lib\iterables.js:76:15)
    at P.next (<anonymous>)
    at zr.onFileContentChanged (C:\Users\micro\AppData\Local\Programs\Tangent\resources\app.asar\__build\bundle\webpack:\tangent_electron\src\common\indexing\Indexer.ts:189:35)
    at C:\Users\micro\AppData\Local\Programs\Tangent\resources\app.asar\__build\bundle\webpack:\tangent_electron\src\main\Workspace.ts:976:20
    at async Promise.all (index 0)
```

**Comment by taylorhadden** [comment]
Thanks for the logs! This should definitely help nail down the issue. Looks like the indexer is stumbling on something.

**Comment by taylorhadden** [comment]
I just noticed that you listed your current Tangent version as v0.6.7. Do you still have this problem in the latest v0.8 beta?
